### ISSUE TITLE
Problemas al asignar giro

### ISSUE THREAD

**Issue by inyerade** [odoo-chile/l10n_cl_partner_activities#1]
Como usuario normal me muestra este mensaje cuando hago click para me me despliegue el listado de giros, al editar un proveedor

> AccessError
> 
> Lo siento, no está autorizado para acceder a este documento. Por favor, contacte con el administrador del sistema si piensa que esto es un error.
> 
> (Modelo de documento: partner.activities)

Pero como administrador no tengo problemas al agregar giros

Hay algun permiso especial qu tenga que tener el usuario?

**Comment by Danisan** [comment]
Si. Se debe a que el módulo en su versión actual no tiene ninguna configuración de seguridad. Por supuesto se aceptan pull requests con los cambios necesarios.
Los giros en el modelo partner activities están todos y no es necesario agregar nuevos, pero si el usuario necesitará permisos para seleccionar giros en el voucher de la factura, y para asignar giros al partner.
En definitiva, como mínimo permisos de lectura en partner.activities, Sugiero asignar permisos al grupo "responsable de ventas".

**Comment by Danisan** [comment]
Los últimos commits deberían haber resuelto ese problema, ya que se agregó security/ir.model.access.csv
